In [2]:
ls

Analyser.py
devstral:24b_BigCodeBench_results.csv
devstral:24b_BigCodeBench_results.json
ErrorAnalyser.ipynb
gemma3:27b_BigCodeBench_results.csv
gemma3:27b_BigCodeBench_results.json
phi4:14b_BigCodeBench_results.csv
phi4:14b_BigCodeBench_results.json
qwen2.5-coder:14b_BigCodeBench_results.csv
qwen2.5-coder:14b_BigCodeBench_results.json
qwen2.5-coder:32b_BigCodeBench_results.csv
qwen2.5-coder:32b_BigCodeBench_results.json
qwen2.5-coder:7b_BigCodeBench_results.csv
qwen2.5-coder:7b_BigCodeBench_results.json
qwen2.5-coder:7b_HumanEval_results.csv
qwen2.5-coder:7b_HumanEval_results.json
qwen2.5-coder:7b_MBPP_results.csv
qwen2.5-coder:7b_MBPP_results.json
qwen2.5:7b_BigCodeBench_results.csv
qwen2.5:7b_BigCodeBench_results.json

In [3]:
import pandas as pd
import os
import ast

In [4]:
files = os.listdir(".")

In [5]:
files

['phi4:14b_BigCodeBench_results.json',
 'qwen2.5-coder:14b_BigCodeBench_results.json',
 'gemma3:27b_BigCodeBench_results.json',
 'qwen2.5-coder:7b_MBPP_results.json',
 'qwen2.5-coder:7b_HumanEval_results.csv',
 'qwen2.5-coder:7b_BigCodeBench_results.json',
 'phi4:14b_BigCodeBench_results.csv',
 'gemma3:27b_BigCodeBench_results.csv',
 'qwen2.5:7b_BigCodeBench_results.csv',
 'ErrorAnalyser.ipynb',
 'devstral:24b_BigCodeBench_results.csv',
 'qwen2.5-coder:7b_BigCodeBench_results.csv',
 'qwen2.5-coder:7b_MBPP_results.csv',
 'qwen2.5-coder:32b_BigCodeBench_results.csv',
 'qwen2.5:7b_BigCodeBench_results.json',
 'qwen2.5-coder:14b_BigCodeBench_results.csv',
 '.ipynb_checkpoints',
 'devstral:24b_BigCodeBench_results.json',
 'qwen2.5-coder:32b_BigCodeBench_results.json',
 'Analyser.py',
 'qwen2.5-coder:7b_HumanEval_results.json']

In [6]:
all_dfs = []
used_files = []

for file in files:
    if not file.endswith("_results.csv"):
        continue
        
    df = pd.read_csv(file)
    if df.shape[1] != 4:
        print(f"Skipping {file} — has {df.shape[1]} columns instead of 4")
        continue
    
    name_part = file.replace("_results.csv", "")
    model,benchmark = name_part.split("_")
    df["model"] = model 
    df["benchmark"] = benchmark
    
    all_dfs.append(df)
    used_files.append(file)

Skipping qwen2.5:7b_BigCodeBench_results.csv — has 3 columns instead of 4

In [7]:
print(used_files)
len(used_files)

['qwen2.5-coder:7b_HumanEval_results.csv', 'phi4:14b_BigCodeBench_results.csv', 'gemma3:27b_BigCodeBench_results.csv', 'devstral:24b_BigCodeBench_results.csv', 'qwen2.5-coder:7b_BigCodeBench_results.csv', 'qwen2.5-coder:7b_MBPP_results.csv', 'qwen2.5-coder:32b_BigCodeBench_results.csv', 'qwen2.5-coder:14b_BigCodeBench_results.csv']

8

In [8]:
# summary=[]

# for i, df in enumerate(all_dfs):
#     summary.append({
        
#         "index":i,
#         "filename":used_files[i],
#         "rows":df.shape[0],
#         "columns":df.shape[1],
#         "column_names": ", ".join(df.columns.tolist())
#     })

In [9]:
# # all_dfs[0].head()
# summary = pd.DataFrame(summary)
# summary

In [10]:
comebined_df = pd.concat(all_dfs, ignore_index=True)

In [11]:
# comebined_df[:60]

comebined_df.head()

,task_id,fix_mode_attempt_count,status,error_trace,model,benchmark
0,0,1,pass,[[None]],qwen2.5-coder:7b,HumanEval
1,1,0,pass,[],qwen2.5-coder:7b,HumanEval
2,2,0,pass,[],qwen2.5-coder:7b,HumanEval
3,3,1,pass,[[None]],qwen2.5-coder:7b,HumanEval
4,4,1,pass,[[None]],qwen2.5-coder:7b,HumanEval

In [12]:
comebined_df.shape

(7978, 6)

In [13]:
fail = comebined_df[comebined_df["status"] == "fail"]

In [14]:
fail.head()

,task_id,fix_mode_attempt_count,status,error_trace,model,benchmark
10,10,5,fail,"[[None], [None], [None], [None], [None]]",qwen2.5-coder:7b,HumanEval
26,26,5,fail,"[[None], [None], [None], [None], [None]]",qwen2.5-coder:7b,HumanEval
32,32,5,fail,"[[None], [None], [None], [None], [None]]",qwen2.5-coder:7b,HumanEval
65,65,5,fail,"[[None], [None], [None], [None], [None]]",qwen2.5-coder:7b,HumanEval
76,76,5,fail,"[[None], [None], [None], [None], [None]]",qwen2.5-coder:7b,HumanEval

In [15]:
# fail["error_trace"].unique()

In [16]:
# fail[:60]
# fail.shape

# fail["error_trace"][170]

In [17]:
# # found_nested_error = False

# for raw_format in fail["error_trace"]:
#     if not raw_format or raw_format == "[]":
#         continue
#     attempts = ast.literal_eval(raw_format)
#     for attempt in attempts:
#         for error in attempt:
            
# #             if isinstance(error, list):
# #                 found_nested_error = True
# #                 print("Found 3rd nested list in:", raw_format)


# # print("Is there a 3rd nested list? ", found_nested_error)

In [18]:
all_errors_detailed = []

for i in range(len(fail)):
    raw = fail["error_trace"].iloc[i]
#     print(i,raw)
#     break
    if not raw or raw == "[]":
        continue
    
    attempts = ast.literal_eval(raw) # make string => list => to loop
#     print(attempts)
#     print(type(attempts))
#     break
    breakpoint() 
    for attempt in attempts:
#         print(attempt)
#         break
#     break
        for error in attempt:
#             print(error)
#             break
#         break
#     break
            if error is not None:
                all_errors_detailed.append({
                    "model": fail["model"].iloc[i],
                    "benchmark": fail["benchmark"].iloc[i],
                    "error": error
                })

print(f"Total errors collected: {len(all_errors_detailed)}")

Total errors collected: 36911

In [19]:
# all_errors_detailed

In [20]:
errors_df = pd.DataFrame(all_errors_detailed)

In [21]:
# print(errors_df.shape)

In [22]:
errors_df.head()

      model     benchmark           error
0  phi4:14b  BigCodeBench  AssertionError
1  phi4:14b  BigCodeBench  AssertionError
2  phi4:14b  BigCodeBench  AssertionError
3  phi4:14b  BigCodeBench  AssertionError
4  phi4:14b  BigCodeBench  AssertionError

In [23]:
# Get the most occur error, overall:

errors_df["error"].value_counts()

NameError                                 16657
AssertionError                            11550
ValueError                                 2306
TypeError                                  1768
FileNotFoundError                          1029
AttributeError                              953
KeyError                                    529
UnknownError                                394
LookupError                                 327
ImportError                                 258
IndexError                                  227
RuntimeError                                202
OSError                                      99
UnicodeDecodeError                           66
ModuleNotFoundError                          65
UnboundLocalError                            47
urllib.error.HTTPError                       43
urllib.error.URLError                        42
textblob.exceptions.MissingCorpusError       35
pandas.errors.LossySetitemError              35
pandas.errors.MergeError                     34
Infinite Loop                                29
subprocess.CalledProcessError                27
SyntaxError                                  26
re.error                                     24
FileExistsError                              19
binascii.Error                               16
pandas.errors.EmptyDataError                 12
requests.exceptions.ConnectionError          11
json.decoder.JSONDecodeError                 10
NotImplementedError                          10
requests.exceptions.HTTPError                 9
OverflowError                                 6
pytz.exceptions.UnknownTimeZoneError          5
ConnectionRefusedError                        5
pandas.errors.DatabaseError                   5
socket.gaierror                               5
ConnectionError                               5
pandas.errors.ParserError                     4
statistics.StatisticsError                    3
pandas.errors.OptionError                     3
pandas.errors.InvalidIndexError               3
numpy.linalg.LinAlgError                      2
ZeroDivisionError                             2
RecursionError                                1
PermissionError                               1
ConnectionResetError                          1
numpy.exceptions.AxisError                    1
Name: error, dtype: int64

In [24]:
error_counts_table = errors_df.groupby(["model", "benchmark"])["error"].value_counts().reset_index(name="count")

In [25]:
# error_counts_table[:50]

In [26]:
# error_counts_table[50:100]

In [60]:
# error_counts_table[100:150]

In [59]:
# error_counts_table[150:169]

In [109]:
# Check to see each model and each benchmark (dataset), which errors occur the most:

top3_table = error_counts_table.sort_values(["model", "benchmark", "count"], ascending=[True, True, False]).groupby(["model", "benchmark"]).head(3)
top3_table

                 model     benchmark           error  count
0         devstral:24b  BigCodeBench       NameError   3453
1         devstral:24b  BigCodeBench  AssertionError   1838
2         devstral:24b  BigCodeBench      ValueError    511
32          gemma3:27b  BigCodeBench       NameError   2358
33          gemma3:27b  BigCodeBench  AssertionError   2062
34          gemma3:27b  BigCodeBench       TypeError    438
60            phi4:14b  BigCodeBench       NameError   4096
61            phi4:14b  BigCodeBench  AssertionError   2371
62            phi4:14b  BigCodeBench      ValueError    506
91   qwen2.5-coder:14b  BigCodeBench       NameError   3596
92   qwen2.5-coder:14b  BigCodeBench  AssertionError   2355
93   qwen2.5-coder:14b  BigCodeBench      ValueError    533
127  qwen2.5-coder:32b  BigCodeBench       NameError   3122
128  qwen2.5-coder:32b  BigCodeBench  AssertionError   1847
129  qwen2.5-coder:32b  BigCodeBench      ValueError    425
160   qwen2.5-coder:7b          MBPP  AssertionError   1077
161   qwen2.5-coder:7b          MBPP       TypeError    101
162   qwen2.5-coder:7b          MBPP       NameError     32

In [89]:
# check to see each data set, which errors occur the most:

benchmark_totals = errors_df.groupby(["benchmark", "error"]).size().reset_index(name="count")

In [102]:
benchmark_totals.sort_values(["benchmark", "count"], ascending=[True, False]).groupby("benchmark").head(3)

       benchmark           error  count
13  BigCodeBench       NameError  16625
0   BigCodeBench  AssertionError  10473
24  BigCodeBench      ValueError   2300
47          MBPP  AssertionError   1077
54          MBPP       TypeError    101
51          MBPP       NameError     32